apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-frontend
  labels:
    app: {{ .Release.Name }}-frontend
spec:
  replicas: {{ .Values.deployment.replicas }}
  template:
    metadata:
      name: {{ .Release.Name }}-frontend
      labels:
        app: {{ .Release.Name }}-frontend
    spec:
      containers:
        - name: frontend
          ports:
            - containerPort: 80
              name: http
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
      restartPolicy: Always
  selector:
    matchLabels:
      app: {{ .Release.Name }}-frontend
