apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
  labels:
    app: {{ .Release.Name }}-backend
spec:
  replicas: {{ .Values.deployment.replicas }}
  template:
    metadata:
      name: {{ .Release.Name }}-backend
      {{- with .Values.deployment.podAnnotations }}
      annotations: {{ toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ .Release.Name }}-backend
    spec:
      initContainers:
        # TODO(fede): Simplify migration process by packaging the database scripts with the image
        - name: migrate-db
          image: docker.io/migrate/migrate:v4.15.1
          imagePullPolicy: IfNotPresent
          command: [ migrate ]
          args:
            - -source
            - github://$(OWNER)/$(REPO)/$(MIGRATIONS_PATH)#$(REF)
            - -database
            - postgres://$(DB_USER):$(DB_PASS)@$(DB_HOST):$(DB_PORT)/$(DB_NAME)?sslmode=$(DB_SSL_MODE)
            - up
          env:
            - name: OWNER
              value: WebEngineeringGroupI
            - name: REPO
              value: backend
            - name: MIGRATIONS_PATH
              value: database/migrate
            - name: REF
              value: {{ .Values.image.tag }}
      {{- include "urlshortener.database.envvars" . | nindent 12 }}
      containers:
        - name: backend
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 8081
              name: grpc
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- include "urlshortener.database.envvars" . | nindent 12 }}
            {{- include "urlshortener.rabbitmq.envvars" . | nindent 12 }}
            - name: BASE_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-backend
                  key: base_hostname
      restartPolicy: Always
  selector:
    matchLabels:
      app: {{ .Release.Name }}-backend
