{{- if (and .Values.monitoring.podMonitor.enabled (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1") ) }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ .Release.Name }}-podmonitor
spec:
  podMetricsEndpoints:
    - port: http
  selector:
    matchLabels:
      app: {{ .Release.Name }}-backend
{{- end }}
