apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-backend-database
data:
  password:  {{ required "A valid database.postgresqlPassword is required" .Values.database.postgresqlPassword | b64enc | quote }}
  username: {{ required "A valid database.postgresqlUsername is required" .Values.database.postgresqlUsername | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-google-safe-browsing
data:
  apiKey:  {{ required "A valid integrations.safebrowsing.apiKey is required" .Values.integrations.safebrowsing.apiKey | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-rabbitmq
data:
  username: {{ required "A valid rabbitmq.username is required" .Values.rabbitmq.username | b64enc | quote }}
  password: {{ required "A valid rabbitmq.password is required" .Values.rabbitmq.password | b64enc | quote }}
