apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-backend-database
data:
  password:  {{ required "A valid .Values.database.postgresqlPassword is required" .Values.database.postgresqlPassword | b64enc | quote }}
  username: {{ required "A valid .Values.database.postgresqlUsername is required" .Values.database.postgresqlUsername | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-google-safe-browsing
data:
  apiKey:  {{ required "A valid .Values.integrations.safebrowsing.apiKey is required" .Values.integrations.safebrowsing.apiKey | b64enc | quote }}
