{{- if .Values.service.http.create }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-http
  {{- with .Values.service.http.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    app: {{ .Release.Name }}-backend
  ports:
  - port: {{ .Values.service.http.port }}
    name: http
    targetPort: 8080
  type: {{ .Values.service.http.type }}
  {{- end }}
  {{- if .Values.service.grpc.create }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-grpc
  {{- with .Values.service.grpc.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    app: {{ .Release.Name }}-backend
  ports:
  - port: {{ .Values.service.grpc.port }}
    name: grpc
    targetPort: 8081
  type: {{ .Values.service.grpc.type }}
  {{- end }}